import type { VendorSpec } from './types';

export const VENDOR_CATALOG: VendorSpec[] = [
  {
    id: 'mir-250',
    name: 'MiR 250',
    category: 'amr',
    vendor: 'Mobile Industrial Robots',
    imageUrl: 'https://mobile-industrial-robots.com/media/2024/02/MiR250_transparent.png',
    unitCostMin: 28000, unitCostMax: 38000,
    payloadKg: 250, speedMph: 3.7, deployWeeks: 8,
    environments: ['warehouse', 'manufacturing', 'retail'],
    processes: ['goods_to_person', 'picking_packing', 'sorting'],
    surfaces: ['smooth_concrete', 'epoxy'],
    requiresDock: false, outdoorCapable: false, minCeilingFt: 7,
    notes: 'Industry-standard AMR. Best for structured warehouse lanes. Excellent fleet management software.',
  },
  {
    id: 'mir-600',
    name: 'MiR 600',
    category: 'amr',
    vendor: 'Mobile Industrial Robots',
    imageUrl: 'https://mobile-industrial-robots.com/media/2024/02/MiR600_transparent.png',
    unitCostMin: 52000, unitCostMax: 68000,
    payloadKg: 600, speedMph: 3.7, deployWeeks: 10,
    environments: ['warehouse', 'manufacturing'],
    processes: ['goods_to_person', 'sorting'],
    surfaces: ['smooth_concrete', 'epoxy', 'rough_concrete'],
    requiresDock: false, outdoorCapable: false, minCeilingFt: 7,
    notes: 'High-payload AMR for heavy goods. Ideal for pallet-level transport in large DCs.',
  },
  {
    id: 'seegrid-palion',
    name: 'Palion AMR',
    category: 'amr',
    vendor: 'SEEGrid',
    imageUrl: 'https://seegrid.com/wp-content/uploads/2022/07/Palion-AMR-front.png',
    unitCostMin: 45000, unitCostMax: 65000,
    payloadKg: 1360, speedMph: 3.5, deployWeeks: 12,
    environments: ['warehouse', 'manufacturing'],
    processes: ['goods_to_person', 'sorting'],
    surfaces: ['smooth_concrete', 'epoxy'],
    requiresDock: true, outdoorCapable: false, minCeilingFt: 8,
    notes: 'Vision-guided (no floor tape/QR). Strong in high-mix manufacturing. Requires dock integration.',
  },
  {
    id: 'boston-stretch',
    name: 'Stretch',
    category: 'amr',
    vendor: 'Boston Dynamics',
    imageUrl: 'https://bostondynamics.com/wp-content/uploads/2021/03/stretch-hero.jpg',
    unitCostMin: 150000, unitCostMax: 200000,
    payloadKg: 23, speedMph: 1.5, deployWeeks: 16,
    environments: ['warehouse'],
    processes: ['picking_packing'],
    surfaces: ['smooth_concrete', 'epoxy', 'rough_concrete'],
    requiresDock: false, outdoorCapable: false, minCeilingFt: 8,
    notes: 'Case-handling robot for trailer unloading. Reduces injury risk. High price point — best for high-volume DCs.',
  },
  {
    id: 'unitree-b2',
    name: 'B2',
    category: 'amr',
    vendor: 'Unitree Robotics',
    imageUrl: 'https://www.unitree.com/images/B2/B2-1.jpg',
    unitCostMin: 18000, unitCostMax: 28000,
    payloadKg: 40, speedMph: 9.3, deployWeeks: 6,
    environments: ['warehouse', 'manufacturing', 'cold_storage'],
    processes: ['inspection', 'delivery_indoor'],
    surfaces: ['smooth_concrete', 'epoxy', 'rough_concrete', 'mixed'],
    requiresDock: false, outdoorCapable: true, minCeilingFt: 6,
    notes: 'Quadruped — handles uneven terrain. Excellent for inspection routes and facilities with obstacles.',
  },
  {
    id: 'unitree-h1',
    name: 'H1',
    category: 'humanoid',
    vendor: 'Unitree Robotics',
    imageUrl: 'https://www.unitree.com/images/H1/H1-1.jpg',
    unitCostMin: 90000, unitCostMax: 120000,
    payloadKg: 30, speedMph: 7.5, deployWeeks: 20,
    environments: ['warehouse', 'manufacturing'],
    processes: ['humanoid_general', 'picking_packing'],
    surfaces: ['smooth_concrete', 'epoxy', 'rough_concrete'],
    requiresDock: false, outdoorCapable: true, minCeilingFt: 7,
    notes: 'Most affordable humanoid. Early commercial stage — best for controlled structured tasks.',
  },
  {
    id: 'agility-digit',
    name: 'Digit',
    category: 'humanoid',
    vendor: 'Agility Robotics',
    imageUrl: 'https://agilityrobotics.com/assets/images/digit-hero.png',
    unitCostMin: 150000, unitCostMax: 250000,
    payloadKg: 16, speedMph: 3.5, deployWeeks: 24,
    environments: ['warehouse'],
    processes: ['humanoid_general', 'picking_packing'],
    surfaces: ['smooth_concrete', 'epoxy'],
    requiresDock: false, outdoorCapable: false, minCeilingFt: 7,
    notes: 'Amazon-backed. Purpose-built for tote movement in fulfillment centers. Best long-term partnership track.',
  },
  {
    id: 'serve-gen3',
    name: 'Serve Gen 3',
    category: 'delivery',
    vendor: 'Serve Robotics',
    imageUrl: 'https://serverobotics.com/wp-content/uploads/2023/06/serve-gen3-robot.png',
    unitCostMin: 20000, unitCostMax: 30000,
    payloadKg: 15, speedMph: 6, deployWeeks: 6,
    environments: ['last_mile', 'campus'],
    processes: ['delivery_outdoor'],
    surfaces: ['outdoor_pavement', 'mixed'],
    requiresDock: false, outdoorCapable: true, minCeilingFt: 0,
    notes: 'Sidewalk delivery. Uber Eats integration. Best for dense urban last-mile or campus food delivery.',
  },
  {
    id: 'kiwibot-leap',
    name: 'Kiwibot Leap',
    category: 'delivery',
    vendor: 'Kiwibot',
    imageUrl: 'https://kiwibot.com/wp-content/uploads/2023/01/kiwibot-leap.png',
    unitCostMin: 15000, unitCostMax: 22000,
    payloadKg: 10, speedMph: 4, deployWeeks: 4,
    environments: ['last_mile', 'campus'],
    processes: ['delivery_outdoor'],
    surfaces: ['outdoor_pavement'],
    requiresDock: false, outdoorCapable: true, minCeilingFt: 0,
    notes: 'Most cost-effective sidewalk delivery bot. Strong on university campuses and food courts.',
  },
  {
    id: 'starship',
    name: 'Starship Bot',
    category: 'delivery',
    vendor: 'Starship Technologies',
    imageUrl: 'https://starship.xyz/wp-content/uploads/2022/03/starship-robot.png',
    unitCostMin: 12000, unitCostMax: 18000,
    payloadKg: 9, speedMph: 4, deployWeeks: 4,
    environments: ['campus', 'last_mile'],
    processes: ['delivery_outdoor'],
    surfaces: ['outdoor_pavement'],
    requiresDock: false, outdoorCapable: true, minCeilingFt: 0,
    notes: 'Proven at scale on university campuses. Flat fee model available. Best brand recognition in segment.',
  },
  {
    id: 'dji-enterprise',
    name: 'DJI Enterprise (Matrice series)',
    category: 'drone',
    vendor: 'DJI',
    imageUrl: 'https://dji-official-fe.djicdn.com/dps/0b2571cae7a95bd3f1dc4df7b43b4e63.png',
    unitCostMin: 8000, unitCostMax: 25000,
    payloadKg: 2.7, speedMph: 45, deployWeeks: 3,
    environments: ['warehouse', 'manufacturing', 'last_mile'],
    processes: ['inspection'],
    surfaces: ['smooth_concrete', 'epoxy', 'rough_concrete', 'outdoor_pavement'],
    requiresDock: false, outdoorCapable: true, minCeilingFt: 15,
    notes: 'Fastest ROI for inventory counting and facility inspection. Requires Part 107 FAA cert for outdoor use.',
  },

  // ─── AMR additions ───────────────────────────────────────────────────────────
  {
    id: 'locus-origin',
    name: 'LocusBot Origin',
    category: 'amr',
    vendor: 'Locus Robotics',
    unitCostMin: 12000, unitCostMax: 18000,
    payloadKg: 45, speedMph: 3.5, deployWeeks: 8,
    environments: ['warehouse'],
    processes: ['picking_packing', 'goods_to_person'],
    surfaces: ['smooth_concrete', 'epoxy'],
    requiresDock: true, outdoorCapable: false, minCeilingFt: 7,
    notes: 'Collaborative picking AMR — workers follow LocusBot to pick locations. RaaS only. 1B+ picks completed across fleet. Unit cost shown is annualized RaaS estimate.',
  },
  {
    id: 'greyorange-ranger',
    name: 'Ranger AMR',
    category: 'amr',
    vendor: 'GreyOrange',
    unitCostMin: 50000, unitCostMax: 80000,
    payloadKg: 600, speedMph: 4.0, deployWeeks: 10,
    environments: ['warehouse', 'retail'],
    processes: ['goods_to_person', 'sorting'],
    surfaces: ['smooth_concrete', 'epoxy'],
    requiresDock: true, outdoorCapable: false, minCeilingFt: 7,
    notes: 'AI-first GTP AMR on GreyMatter platform. Adapts to real-time SKU velocity. Best for high-mix, high-throughput e-commerce DCs.',
  },
  {
    id: 'geekplus-p800',
    name: 'P800R Goods-to-Person',
    category: 'amr',
    vendor: 'Geek+',
    unitCostMin: 30000, unitCostMax: 55000,
    payloadKg: 800, speedMph: 4.3, deployWeeks: 10,
    environments: ['warehouse', 'retail'],
    processes: ['goods_to_person', 'sorting'],
    surfaces: ['smooth_concrete', 'epoxy'],
    requiresDock: true, outdoorCapable: false, minCeilingFt: 8,
    notes: 'High-density GTP AMR at 800 kg shelf payload. 3x human efficiency. Used at scale in major global e-commerce DCs. 2–3 month deployment.',
  },
  {
    id: 'otto-750',
    name: 'OTTO 750',
    category: 'amr',
    vendor: 'OTTO Motors',
    unitCostMin: 55000, unitCostMax: 80000,
    payloadKg: 340, speedMph: 4.5, deployWeeks: 8,
    environments: ['warehouse', 'manufacturing'],
    processes: ['goods_to_person', 'delivery_indoor'],
    surfaces: ['smooth_concrete', 'epoxy', 'rough_concrete'],
    requiresDock: false, outdoorCapable: false, minCeilingFt: 7,
    notes: 'Rockwell Automation subsidiary. Industrial-grade manufacturing floor AMR. Strong in automotive and heavy industrial. Dealer network via Toyota MHS, Papé.',
  },
  {
    id: 'omron-ld250',
    name: 'LD-250',
    category: 'amr',
    vendor: 'Omron Mobile Robotics',
    unitCostMin: 40000, unitCostMax: 60000,
    payloadKg: 250, speedMph: 4.3, deployWeeks: 6,
    environments: ['warehouse', 'manufacturing', 'retail'],
    processes: ['goods_to_person', 'delivery_indoor'],
    surfaces: ['smooth_concrete', 'epoxy'],
    requiresDock: false, outdoorCapable: false, minCeilingFt: 7,
    notes: 'Mid-range AMR with wide distributor network. Best for sites already on Omron PLCs (NX/NJ) for seamless control system integration.',
  },
  {
    id: 'hai-a42n',
    name: 'HAIPICK A42N',
    category: 'amr',
    vendor: 'HAI Robotics',
    unitCostMin: 25000, unitCostMax: 45000,
    payloadKg: 30, speedMph: 3.5, deployWeeks: 10,
    environments: ['warehouse', 'retail'],
    processes: ['picking_packing', 'goods_to_person'],
    surfaces: ['smooth_concrete', 'epoxy'],
    requiresDock: true, outdoorCapable: false, minCeilingFt: 16,
    notes: "World's first carton-picking ACR: 4.5m vertical reach for multi-level tote retrieval. Best for high-density small-item storage maximizing vertical space.",
  },
  {
    id: 'clearpath-husky',
    name: 'Husky UGV',
    category: 'amr',
    vendor: 'Clearpath Robotics',
    unitCostMin: 22000, unitCostMax: 35000,
    payloadKg: 75, speedMph: 3.7, deployWeeks: 4,
    environments: ['warehouse', 'manufacturing'],
    processes: ['inspection', 'delivery_indoor'],
    surfaces: ['smooth_concrete', 'epoxy', 'rough_concrete', 'mixed'],
    requiresDock: false, outdoorCapable: true, minCeilingFt: 5,
    notes: 'ROS2 research and commercial UGV. IP54. Rockwell Automation subsidiary. Best for custom sensor payloads, inspection routes, and R&D deployments.',
  },

  // ─── HUMANOID additions ──────────────────────────────────────────────────────
  {
    id: 'apptronik-apollo',
    name: 'Apollo',
    category: 'humanoid',
    vendor: 'Apptronik',
    unitCostMin: 100000, unitCostMax: 250000,
    payloadKg: 25, speedMph: 4.0, deployWeeks: 24,
    environments: ['warehouse', 'manufacturing'],
    processes: ['humanoid_general', 'picking_packing'],
    surfaces: ['smooth_concrete', 'epoxy', 'rough_concrete'],
    requiresDock: false, outdoorCapable: false, minCeilingFt: 7,
    notes: 'NASA-backed humanoid. Partners: GE Aerospace, Mercedes-Benz, GXO. 4-hr battery. Industrial pilot programs. Target <$50K long-term.',
  },
  {
    id: 'ubtech-walker-s2',
    name: 'Walker S2',
    category: 'humanoid',
    vendor: 'UBTECH Robotics',
    unitCostMin: 180000, unitCostMax: 180000,
    payloadKg: 10, speedMph: 3.1, deployWeeks: 20,
    environments: ['manufacturing', 'warehouse'],
    processes: ['humanoid_general'],
    surfaces: ['smooth_concrete', 'epoxy'],
    requiresDock: false, outdoorCapable: false, minCeilingFt: 7,
    notes: 'Mass production Nov 2025. $180K purchase or $5K/mo RaaS. Best-documented commercial humanoid deployment: BYD, Geely, FAW-VW, Foxconn.',
  },
  {
    id: 'fourier-gr1',
    name: 'GR-1',
    category: 'humanoid',
    vendor: 'Fourier Intelligence',
    unitCostMin: 149999, unitCostMax: 170000,
    payloadKg: 30, speedMph: 3.1, deployWeeks: 16,
    environments: ['warehouse', 'manufacturing'],
    processes: ['humanoid_general', 'picking_packing'],
    surfaces: ['smooth_concrete', 'epoxy', 'rough_concrete'],
    requiresDock: false, outdoorCapable: false, minCeilingFt: 7,
    notes: '42 DOF. Active research deployments globally. Rehabilitation and industrial piloting. Mass production target 2026.',
  },
  {
    id: 'agibot-a2',
    name: 'A2 Standard',
    category: 'humanoid',
    vendor: 'AgiBot',
    unitCostMin: 100000, unitCostMax: 160000,
    payloadKg: 15, speedMph: 2.5, deployWeeks: 18,
    environments: ['manufacturing', 'warehouse'],
    processes: ['humanoid_general', 'picking_packing'],
    surfaces: ['smooth_concrete', 'epoxy'],
    requiresDock: false, outdoorCapable: false, minCeilingFt: 7,
    notes: 'Whole-body dexterous manipulation. A2 Standard $100K; A2-Max up to $160K; Youth Edition $23K. Also available RaaS at €899/day.',
  },

  // ─── DRONE additions ─────────────────────────────────────────────────────────
  {
    id: 'autel-evo-max',
    name: 'EVO Max 4T V2',
    category: 'drone',
    vendor: 'Autel Robotics',
    unitCostMin: 9000, unitCostMax: 14000,
    payloadKg: 0.9, speedMph: 45, deployWeeks: 2,
    environments: ['warehouse', 'manufacturing', 'last_mile'],
    processes: ['inspection'],
    surfaces: ['smooth_concrete', 'epoxy', 'rough_concrete', 'outdoor_pavement'],
    requiresDock: false, outdoorCapable: true, minCeilingFt: 15,
    notes: 'NDAA-compliant DJI alternative. Quad-sensor fusion (thermal + zoom + wide + laser). 42-min flight, 20km range. Best for DOD/gov-adjacent contracts.',
  },
  {
    id: 'parrot-anafi-usa',
    name: 'ANAFI USA',
    category: 'drone',
    vendor: 'Parrot',
    unitCostMin: 7000, unitCostMax: 8000,
    payloadKg: 0.3, speedMph: 37, deployWeeks: 2,
    environments: ['warehouse', 'manufacturing'],
    processes: ['inspection'],
    surfaces: ['smooth_concrete', 'epoxy', 'rough_concrete', 'outdoor_pavement'],
    requiresDock: false, outdoorCapable: true, minCeilingFt: 12,
    notes: 'NDAA/TAA compliant, Blue sUAS approved (DIU), NATO-approved, US-assembled. IP53. Best compliance posture of any commercial drone platform.',
  },
  {
    id: 'percepto-sparrow',
    name: 'Sparrow / Arc (Drone-in-a-Box)',
    category: 'drone',
    vendor: 'Percepto',
    unitCostMin: 60000, unitCostMax: 120000,
    payloadKg: 0.5, speedMph: 36, deployWeeks: 6,
    environments: ['manufacturing', 'warehouse'],
    processes: ['inspection'],
    surfaces: ['smooth_concrete', 'epoxy', 'rough_concrete', 'outdoor_pavement'],
    requiresDock: true, outdoorCapable: true, minCeilingFt: 15,
    notes: 'Autonomous drone-in-a-box with BVLOS approval. SaaS platform includes dock, AI analytics, and reporting. Best for 24/7 autonomous perimeter and facility inspection.',
  },
];
