import type { VendorSpec } from './types';

export const VENDOR_CATALOG: VendorSpec[] = [
  {
    id: 'mir-250',
    name: 'MiR 250',
    category: 'amr',
    vendor: 'Mobile Industrial Robots',
    unitCostMin: 28000, unitCostMax: 38000,
    payloadKg: 250, speedMph: 3.7, deployWeeks: 8,
    environments: ['warehouse', 'manufacturing', 'retail'],
    processes: ['goods_to_person', 'picking_packing', 'sorting'],
    surfaces: ['smooth_concrete', 'epoxy'],
    requiresDock: false, outdoorCapable: false, minCeilingFt: 7,
    notes: 'Industry-standard AMR. Best for structured warehouse lanes. Excellent fleet management software.',
  },
  {
    id: 'mir-600',
    name: 'MiR 600',
    category: 'amr',
    vendor: 'Mobile Industrial Robots',
    unitCostMin: 52000, unitCostMax: 68000,
    payloadKg: 600, speedMph: 3.7, deployWeeks: 10,
    environments: ['warehouse', 'manufacturing'],
    processes: ['goods_to_person', 'sorting'],
    surfaces: ['smooth_concrete', 'epoxy', 'rough_concrete'],
    requiresDock: false, outdoorCapable: false, minCeilingFt: 7,
    notes: 'High-payload AMR for heavy goods. Ideal for pallet-level transport in large DCs.',
  },
  {
    id: 'seegrid-palion',
    name: 'Palion AMR',
    category: 'amr',
    vendor: 'SEEGrid',
    unitCostMin: 45000, unitCostMax: 65000,
    payloadKg: 1360, speedMph: 3.5, deployWeeks: 12,
    environments: ['warehouse', 'manufacturing'],
    processes: ['goods_to_person', 'sorting'],
    surfaces: ['smooth_concrete', 'epoxy'],
    requiresDock: true, outdoorCapable: false, minCeilingFt: 8,
    notes: 'Vision-guided (no floor tape/QR). Strong in high-mix manufacturing. Requires dock integration.',
  },
  {
    id: 'boston-stretch',
    name: 'Stretch',
    category: 'amr',
    vendor: 'Boston Dynamics',
    unitCostMin: 150000, unitCostMax: 200000,
    payloadKg: 23, speedMph: 1.5, deployWeeks: 16,
    environments: ['warehouse'],
    processes: ['picking_packing'],
    surfaces: ['smooth_concrete', 'epoxy', 'rough_concrete'],
    requiresDock: false, outdoorCapable: false, minCeilingFt: 8,
    notes: 'Case-handling robot for trailer unloading. Reduces injury risk. High price point — best for high-volume DCs.',
  },
  {
    id: 'unitree-b2',
    name: 'B2',
    category: 'amr',
    vendor: 'Unitree Robotics',
    unitCostMin: 18000, unitCostMax: 28000,
    payloadKg: 40, speedMph: 9.3, deployWeeks: 6,
    environments: ['warehouse', 'manufacturing', 'cold_storage'],
    processes: ['inspection', 'delivery_indoor'],
    surfaces: ['smooth_concrete', 'epoxy', 'rough_concrete', 'mixed'],
    requiresDock: false, outdoorCapable: true, minCeilingFt: 6,
    notes: 'Quadruped — handles uneven terrain. Excellent for inspection routes and facilities with obstacles.',
  },
  {
    id: 'unitree-h1',
    name: 'H1',
    category: 'humanoid',
    vendor: 'Unitree Robotics',
    unitCostMin: 90000, unitCostMax: 120000,
    payloadKg: 30, speedMph: 7.5, deployWeeks: 20,
    environments: ['warehouse', 'manufacturing'],
    processes: ['humanoid_general', 'picking_packing'],
    surfaces: ['smooth_concrete', 'epoxy', 'rough_concrete'],
    requiresDock: false, outdoorCapable: true, minCeilingFt: 7,
    notes: 'Most affordable humanoid. Early commercial stage — best for controlled structured tasks.',
  },
  {
    id: 'agility-digit',
    name: 'Digit',
    category: 'humanoid',
    vendor: 'Agility Robotics',
    unitCostMin: 150000, unitCostMax: 250000,
    payloadKg: 16, speedMph: 3.5, deployWeeks: 24,
    environments: ['warehouse'],
    processes: ['humanoid_general', 'picking_packing'],
    surfaces: ['smooth_concrete', 'epoxy'],
    requiresDock: false, outdoorCapable: false, minCeilingFt: 7,
    notes: 'Amazon-backed. Purpose-built for tote movement in fulfillment centers. Best long-term partnership track.',
  },
  {
    id: 'serve-gen3',
    name: 'Serve Gen 3',
    category: 'delivery',
    vendor: 'Serve Robotics',
    unitCostMin: 20000, unitCostMax: 30000,
    payloadKg: 15, speedMph: 6, deployWeeks: 6,
    environments: ['last_mile', 'campus'],
    processes: ['delivery_outdoor'],
    surfaces: ['outdoor_pavement', 'mixed'],
    requiresDock: false, outdoorCapable: true, minCeilingFt: 0,
    notes: 'Sidewalk delivery. Uber Eats integration. Best for dense urban last-mile or campus food delivery.',
  },
  {
    id: 'kiwibot-leap',
    name: 'Kiwibot Leap',
    category: 'delivery',
    vendor: 'Kiwibot',
    unitCostMin: 15000, unitCostMax: 22000,
    payloadKg: 10, speedMph: 4, deployWeeks: 4,
    environments: ['last_mile', 'campus'],
    processes: ['delivery_outdoor'],
    surfaces: ['outdoor_pavement'],
    requiresDock: false, outdoorCapable: true, minCeilingFt: 0,
    notes: 'Most cost-effective sidewalk delivery bot. Strong on university campuses and food courts.',
  },
  {
    id: 'starship',
    name: 'Starship Bot',
    category: 'delivery',
    vendor: 'Starship Technologies',
    unitCostMin: 12000, unitCostMax: 18000,
    payloadKg: 9, speedMph: 4, deployWeeks: 4,
    environments: ['campus', 'last_mile'],
    processes: ['delivery_outdoor'],
    surfaces: ['outdoor_pavement'],
    requiresDock: false, outdoorCapable: true, minCeilingFt: 0,
    notes: 'Proven at scale on university campuses. Flat fee model available. Best brand recognition in segment.',
  },
  {
    id: 'dji-enterprise',
    name: 'DJI Enterprise (Matrice series)',
    category: 'drone',
    vendor: 'DJI',
    unitCostMin: 8000, unitCostMax: 25000,
    payloadKg: 2.7, speedMph: 45, deployWeeks: 3,
    environments: ['warehouse', 'manufacturing', 'last_mile'],
    processes: ['inspection'],
    surfaces: ['smooth_concrete', 'epoxy', 'rough_concrete', 'outdoor_pavement'],
    requiresDock: false, outdoorCapable: true, minCeilingFt: 15,
    notes: 'Fastest ROI for inventory counting and facility inspection. Requires Part 107 FAA cert for outdoor use.',
  },
];
